package game;

import login.startPanel;
import matrixPanel.createMatrix;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;

public class gamePanel extends JPanel {
    private JFrame window ;
    private createMatrix matrix ;
    public gamePanel(JPanel matrix , JFrame window) {
        this.matrix = (createMatrix) matrix;
        this.window = window ;
        initComponents();
        boardContainer.setLayout(new BorderLayout());
        boardContainer.add(matrix, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        Restart = new javax.swing.JButton();
        Menu = new javax.swing.JButton();
        boardContainer = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(760, 594));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(760, 594));

        Restart.setText("Restart");
        Restart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestartActionPerformed(evt);
            }
        });


        Menu.setText("Menu");
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });

        boardContainer.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 153, 153), new java.awt.Color(255, 102, 102)));
        boardContainer.setMaximumSize(new java.awt.Dimension(570, 570));
        boardContainer.setMinimumSize(new java.awt.Dimension(350, 350));
        boardContainer.setPreferredSize(new java.awt.Dimension(570, 570));

        javax.swing.GroupLayout boardContainerLayout = new javax.swing.GroupLayout(boardContainer);
        boardContainer.setLayout(boardContainerLayout);
        boardContainerLayout.setHorizontalGroup(
                boardContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 566, Short.MAX_VALUE)
        );
        boardContainerLayout.setVerticalGroup(
                boardContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 566, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(boardContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Menu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Restart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(90, 90, 90)
                                                .addComponent(Restart, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGap(18, 18, 18)
                                                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(boardContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(11, Short.MAX_VALUE))
        );
    }// </editor-fold>

    private void RestartActionPerformed(ActionEvent evt) {
         matrix.reset() ;
    }

    private void UndoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {
        window.getContentPane().removeAll();
        window.setContentPane(new startPanel(window));
        window.pack();
    }


    // Variables declaration - do not modify
    private javax.swing.JButton Menu;
    private javax.swing.JButton Restart;

    private javax.swing.JPanel boardContainer;
    // End of variables declaration
}
