import database.HighScore;
import database.HighScores;

import java.sql.SQLException;
import java.util.ArrayList;

public class GameOverFrame extends javax.swing.JFrame {

    private final int score;
    private final Board board;

    public GameOverFrame(int score, Board board) {
        this.score = score;
        this.board = board;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        playerName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        SaveScore = new javax.swing.JButton();
        restart = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        scorePrint = new javax.swing.JLabel();

        setLocation(new java.awt.Point(300, 300));
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 200));
        setResizable(false);
        setVisible(true);

        playerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerNameActionPerformed(evt);
            }
        });

        jLabel1.setText("name");

        SaveScore.setText("Save score");
        SaveScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveScoreActionPerformed(evt);
            }
        });

        restart.setText("Play again");
        restart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartActionPerformed(evt);
            }
        });

        jLabel2.setText("score");

        scorePrint.setText(String.valueOf(score));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 59, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(SaveScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(restart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(playerName))
                                        .addComponent(scorePrint))
                                .addGap(96, 96, 96))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(scorePrint))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(playerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SaveScore)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(restart)
                                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void SaveScoreActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            HighScores highScores = new HighScores(10);
            highScores.putHighScore(playerName.getText(), score);
            SaveScore.setEnabled(false);
        } catch (SQLException throwables) {
            throwables.printStackTrace();
        }
    }

    private void restartActionPerformed(java.awt.event.ActionEvent evt) {
        new Snake();
        this.dispose();
    }

    private void playerNameActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }


    // Variables declaration - do not modify
    private javax.swing.JButton SaveScore;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField playerName;
    private javax.swing.JButton restart;
    private javax.swing.JLabel scorePrint;
    // End of variables declaration
}
